service:
  name: Client Dev Service
server:
  port: 8200
example:
  message: This is a dev properties
encrypted:
  property: AgBvEnUt7IzEaQXG5u59yp6mOLZzReYdnUQQTjonf6fqgBu6QGDsmnbP1kQXWoJBpXEbkHY665Qk3iocYzPAnCOehhVyUuh9yfi3mxsiWfJR/Z89vvgmar6kC+FAwi+9+nu9IFhpuZuEe1zZHVUDBwIgjR/dROur/RtHkWd4S3aHgqCt2olNSsN5MNbH6YjjQvQcNh9hs7jUhtl6+L3nS6qZBGrmLqbF/Gwm3DBdg3+YDO0Pzyk/ItuJs26qWc8fWU8iiQpQYwgS0LWZMClhBxhjnzTTSFouGmIeLH+yKSIz6pqacbIdfFdo8m9Y8FvcCvTH9GqEAqH7L+u7F6ym3WTTHIsjnWwRoNwaLjVMV59Ei9UTfhJYMIrFlvw+1NuXoVzPy0+UWVMtbsR2AhF1wIJNeF+ucFcLmave6g6wkbEgVJqNFEGg9oZ/VVMLrW3xjIfQPryxJXSr4Fy0fm/j+Q8hmOj1s+MFQt/T3pcl2C3TnaZUVA88QGG3qjHe10jWzBOqfNZ7J1JsHNAdwq/+OTEhagUTyb5zQ3z4FcppFBLufeOvWgNOI56OxTpHob4xfGudHZ+ZyY3rCX+nDiR1RMaQUoWtJsYtqy7QZ8G4Grvjsj2D+z1XuFwNoI1BxLw+JjU6cDk29MB7ZTCkYP0zPAa7NeqQxmDEREPOnD+r/PtbuhIQGZrQoErvpweJNiL9oAY6RGUlxobhBhgUB8NOmyyl
