service:
  name: Client Dev Service
server:
  port: 8200
example:
  message: This is a dev properties
encrypted:
  property: '{cipher}c789b2ee5bdfd2ab95b7b13d115596485408a82bfb3ba599199b356673a0b949'
